name: Auto Parse DouYu Livestreams

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  parse-livestreams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests execjs

      - name: Run Script
        run: |
          python parse_livestreams.py

      - name: Commit and Push Output
        run: |
        steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
  with:
    node-version: '20'  # 指定版本
- run: npm install
- run: npm build
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.txt
          git commit -m "Update output file" || echo "No changes to commit"
          git push origin HEAD
